export const LANGUAGES = ['en', 'zh'] as const

export type Language = (typeof LANGUAGES)[number]

export const translations = {
  en: {
    agentPrompt: 'Agent prompt',
    anyCategory: 'Any category',
    anyMarketplace: 'Any marketplace',
    anyTag: 'Any tag',
    binaryPreviewUnavailable: 'Preview unavailable for binary or large files.',
    category: 'Category',
    copyContent: 'copy content',
    copyInstall: 'copy install',
    copyInstallCommand: 'Copy install command',
    fileContentMissing: 'File content is not in the generated catalog.',
    files: 'Files',
    globalSetupDescription: 'Add this marketplace once, then install plugins from their detail panel.',
    globalSetupTitle: 'Global setup',
    hubRepo: 'hub repo',
    install: 'Install',
    installDescription: 'Prompt an agent, or run the commands manually.',
    inventory: 'Inventory',
    language: 'Language',
    lastSync: 'last sync',
    license: 'License',
    loadPluginToBrowse: 'Load a plugin to browse files.',
    loadingCatalog: 'Loading catalog...',
    maintainer: 'Maintainer',
    marketplace: 'marketplace',
    marketplaceFilter: 'Marketplace',
    missingHubMetadata: 'Missing `.jthewl-hub` metadata. Showing marketplace fields only.',
    noDefaultPreview: 'This plugin has no default preview file.',
    noFileSelected: 'No file selected',
    noMatchingPlugins: 'No matching plugins.',
    noPlugin: 'no plugin',
    noPreviewTree: 'No previewable tree.',
    openHubRepo: 'Open hub GitHub repository',
    openPluginSource: 'Open plugin source',
    openSkillsMarketplace: 'Open skills marketplace GitHub repository',
    path: 'path',
    plugin: 'Plugin',
    pluginBrowser: 'Plugin browser',
    pluginDetail: 'Plugin detail',
    pluginFileExplorer: 'Plugin file explorer',
    pluginFilters: 'Plugin filters',
    plugins: 'plugins',
    rawFallback: 'raw fallback',
    searchPlaceholder: 'Search plugins, tags, use cases',
    selectPlugin: 'Select a plugin to inspect details.',
    skillsMarketplace: 'skills marketplace',
    source: 'Source',
    tag: 'Tag',
    textFile: 'text',
    uncategorized: 'Uncategorized',
    unknown: 'unknown',
    unknownMarketplace: 'Unknown marketplace',
    unknownMaintainer: 'Unknown',
    unspecified: 'Unspecified',
    updatedRecently: 'Updated recently',
    useCases: 'Use cases',
    viewRaw: 'view raw',
    warnings: 'Warnings',
  },
  zh: {
    agentPrompt: 'Agent 提示词',
    anyCategory: '任意分类',
    anyMarketplace: '任意市场',
    anyTag: '任意标签',
    binaryPreviewUnavailable: '二进制或大型文件不可预览。',
    category: '分类',
    copyContent: '复制内容',
    copyInstall: '复制安装命令',
    copyInstallCommand: '复制安装命令',
    fileContentMissing: '生成目录中没有收录这个文件内容。',
    files: '文件',
    globalSetupDescription: '先添加一次这个市场，然后在详情面板中安装插件。',
    globalSetupTitle: '全局设置',
    hubRepo: 'hub 仓库',
    install: '安装',
    installDescription: '复制 Agent 提示词，或手动运行命令。',
    inventory: '清单',
    language: '语言',
    lastSync: '最后同步',
    license: '许可证',
    loadPluginToBrowse: '加载插件后浏览文件。',
    loadingCatalog: '正在加载目录...',
    maintainer: '维护者',
    marketplace: '市场',
    marketplaceFilter: '市场',
    missingHubMetadata: '缺少 `.jthewl-hub` 元数据。当前只显示 marketplace 字段。',
    noDefaultPreview: '这个插件没有默认预览文件。',
    noFileSelected: '未选择文件',
    noMatchingPlugins: '没有匹配的插件。',
    noPlugin: '无插件',
    noPreviewTree: '没有可预览的文件树。',
    openHubRepo: '打开 hub GitHub 仓库',
    openPluginSource: '打开插件源码',
    openSkillsMarketplace: '打开 skills marketplace GitHub 仓库',
    path: '路径',
    plugin: '插件',
    pluginBrowser: '插件浏览器',
    pluginDetail: '插件详情',
    pluginFileExplorer: '插件文件浏览器',
    pluginFilters: '插件筛选',
    plugins: '插件',
    rawFallback: '原始文件',
    searchPlaceholder: '搜索插件、标签、使用场景',
    selectPlugin: '选择插件以查看详情。',
    skillsMarketplace: 'skills 市场',
    source: '来源',
    tag: '标签',
    textFile: '文本',
    uncategorized: '未分类',
    unknown: '未知',
    unknownMarketplace: '未知市场',
    unknownMaintainer: '未知',
    unspecified: '未声明',
    updatedRecently: '最近更新',
    useCases: '使用场景',
    viewRaw: '查看原始文件',
    warnings: '注意事项',
  },
} as const satisfies Record<Language, Record<string, string>>

export type TranslationKey = keyof (typeof translations)['en']

export function isLanguage(value: string | null | undefined): value is Language {
  return LANGUAGES.includes(value as Language)
}

export function resolveLanguage(
  savedLanguage: string | null | undefined,
  browserLanguages: readonly string[] = [],
): Language {
  if (isLanguage(savedLanguage)) return savedLanguage
  if (browserLanguages.some((language) => language.toLowerCase().startsWith('zh'))) return 'zh'
  return 'en'
}

export function t(language: Language, key: TranslationKey) {
  return translations[language][key]
}
